# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phone.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'phone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bphone.proto\x12\ttelemetry\"\xfc\x01\n\x16TelemetryStreamCommand\x12\x38\n\x05start\x18\x01 \x01(\x0b\x32\'.telemetry.TelemetryStreamCommand.StartH\x00\x12;\n\x07get_one\x18\x02 \x01(\x0b\x32(.telemetry.TelemetryStreamCommand.GetOneH\x00\x12\x34\n\x03\x61\x63k\x18\x03 \x01(\x0b\x32%.telemetry.TelemetryStreamCommand.AckH\x00\x1a\x08\n\x06GetOne\x1a\x19\n\x05Start\x12\x10\n\x08\x64uration\x18\x01 \x01(\x01\x1a\x05\n\x03\x41\x63kB\t\n\x07\x63ommand\"\xa7\x01\n\tTelemetry\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12/\n\x08location\x18\x02 \x01(\x0b\x32\x1d.telemetry.Telemetry.Location\x1aX\n\x08Location\x12\'\n\ttimestamp\x18\x01 \x01(\x0b\x32\x14.telemetry.Timestamp\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x32g\n\x10TelemetryService\x12S\n\x12SetTelemetryStream\x12\x14.telemetry.Telemetry\x1a!.telemetry.TelemetryStreamCommand\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYSTREAMCOMMAND']._serialized_start=27
  _globals['_TELEMETRYSTREAMCOMMAND']._serialized_end=279
  _globals['_TELEMETRYSTREAMCOMMAND_GETONE']._serialized_start=226
  _globals['_TELEMETRYSTREAMCOMMAND_GETONE']._serialized_end=234
  _globals['_TELEMETRYSTREAMCOMMAND_START']._serialized_start=236
  _globals['_TELEMETRYSTREAMCOMMAND_START']._serialized_end=261
  _globals['_TELEMETRYSTREAMCOMMAND_ACK']._serialized_start=263
  _globals['_TELEMETRYSTREAMCOMMAND_ACK']._serialized_end=268
  _globals['_TELEMETRY']._serialized_start=282
  _globals['_TELEMETRY']._serialized_end=449
  _globals['_TELEMETRY_LOCATION']._serialized_start=361
  _globals['_TELEMETRY_LOCATION']._serialized_end=449
  _globals['_TIMESTAMP']._serialized_start=451
  _globals['_TIMESTAMP']._serialized_end=494
  _globals['_TELEMETRYSERVICE']._serialized_start=496
  _globals['_TELEMETRYSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
